### ISSUE TITLE
feature: use contentDimensionsByNameForSite eel helper for dimensions

### ISSUE THREAD

**Issue by adrian-cerdeira** [punktDe/sitespecifics#7]
Is it not possible to use the EEL-Helper also in Fusion to for example only show in an language menu allowed presets:
```
    @context.allowedPresetsForLanguage = ${Neos.Ui.Api.emptyArrayToObject(
        PunktDe.SiteSpecifics.SiteSpecificContentDimensions.allowedPresetsByNameForSite(
            documentNode.context.dimensions,
            site
        )
    )}

    renderer = Ongoing.Theme.Menu:Component.Menu {
        @context.menuItems = Neos.Neos:DimensionsMenuItems {
            dimension = 'language'
            presets = ${contentDimensions.allowedPresets['language']}
        }
```

**Comment by adrian-cerdeira** [comment]
It would just need in the settings this code:
```
Neos:
  Fusion:
    defaultContext:
      PunktDe.SiteSpecifics.SiteSpecificContentDimensions: \PunktDe\SiteSpecifics\Eel\SiteSpecificContentDimensionsHelper
```
