### ISSUE TITLE
`showInCreationDialog` config does not work

### ISSUE THREAD

**Issue by connykaelinvisol** [punktDe/sitespecifics#8]
I want to handle properties using SiteSpecifics which should be shown in the Creation Dialog but this config is not working.

Example:
I have a "News" NodeType which has a property "category" on one site and "topic" on another site. These properties should be shown in the Creation Dialog so I setup the properties in my NodeType and added the `showInCreationDialog` config in the SiteSpecifics setting. No matter on which site I create a new Node, I can still see both properties in the Creation Dialog.

Here are the settings:
````
PunktDe:
  SiteSpecifics:
    'My site without categories':
      nodeTypes:
        'My.Site:Document.News':
          properties:
            topics:
              ui:
                showInCreationDialog: true
            # No categories on this site
            categories:
              ui:
                showInCreationDialog: false
                inspector:
                  group: ~
````

````
PunktDe:
  SiteSpecifics:
    'My site without topics':
      nodeTypes:
        'My.Site:Document.News':
          properties:
            # No topics on this site
            topics:
              ui:
                showInCreationDialog: false
                inspector:
                  group: ~
            categories:
              ui:
                showInCreationDialog: true
````

Any other config work fine ☺️

**Comment by daniellienert** [comment]
Hey @connykaelinvisol, thanks for reporting that issue. There is a `CreationDialogPostprocessor` that uses the same mechanic as the `SiteSpecificNodeTypePostProcessor` to alter the nodetype configuration. I guess we need to adjust the loading order of these processors.

**Comment by daniellienert** [comment]
Could you try to adjust the position of the `SiteSpecificNodeTypePostProcessor` in `Packages/Application/PunktDe.SiteSpecifics/Configuration/NodeTypes.Override.Node.yaml` to run before the `CreationDialogPostprocessor` like this: 

```
'Neos.Neos:Node':
  postprocessors:
    'SiteSpecificNodeTypePostProcessor':
      postprocessor: 'PunktDe\SiteSpecifics\NodeTypePostProcessor\SiteSpecificNodeTypePostProcessor'
      position: "before CreationDialogPostprocessor"
```

Does that fix your issue?
